### ISSUE TITLE
Document API exposed from backend to frontend

### ISSUE THREAD

**Issue by disdi** [cargator/cargator-backend#2]
Would it possible to document and publish APIs that backend and frontend use to interact.
This can help to integrate it also to  existing in-vehicle infotainment (IVI) systems.

Refer [CES 2024 demo](https://www.ics.com/blog/racing-toward-ces-exciting-new-ui-automotive-grade-linux-ivi-demo).

**Comment by mrjain** [comment]
Hi, thanks for the feature request we will review and add it to the product roadmap
